helm_deploy/whereabouts-api/templates/_envs.tpl
helm_deploy/whereabouts-api/templates/deployment.yaml
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/CreateAttendanceDto.java
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceService.java
src/main/resources/application-postgres.properties
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/AttendanceIntegrationTest.kt

- Fix elite2 health check
- Tweak validation so it works locally

NN-1897 fix elite2 health check config

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceService.java
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceServiceTest.kt

Updated IEP warnings handler to prevent multiple amendments showing when warning type is changed.  Updated IEP warning test to prove amendments are no longer duped.

NN-2032 Updated IEP warnings

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/config/ResourceServerConfiguration.java
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/config/RestTemplateConfiguration.java
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/NomisService.java

Ensure the token management is request scope so that the correct username is used when requesting a client token.

NN-2011 fix bug around client creds.

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/AttendanceController.java
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/repository/AttendanceRepository.java
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceService.java
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceServiceTest.kt

This endpoint will power various statistics regarding offender attendance of activities.
For https://dsdmoj.atlassian.net/browse/NN-2087 and https://dsdmoj.atlassian.net/browse/NN-2079

NN-2087: Add endpoint for absences

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/AttendanceController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/repository/AttendanceRepository.java
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceExists.java
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceService.java
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/AttendanceIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/wiremock/Elite2MockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceServiceTest.kt

NN-2342: Throw error if user tries to create an attendance when one already exists

Nn 2342 throw error if attendance exists

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/config/AttendanceServiceForAppScope.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/ControllerAdvice.java
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/CourtController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/AppointmentDtos.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/CourtService.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/Exceptions.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/CourtIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/CourtServiceTest.kt

* Remove nullable properties on dto
* Validate court value
* Convert start and end time properties to LocalDateTime to take advantage of standard date validation

NN-2413 Add video link appointment part 2 

---

build.gradle
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/AppointmentDtos.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/CourtService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/CourtServiceTest.kt

Reverts ministryofjustice/whereabouts-api#154

Revert "Nn 2519 return extra court appointment info"

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/CourtService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/CourtIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/CourtServiceTest.kt

The users can now either choose from a dropdown or enter a custom free text value.

NN-2519 remove court validation

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/AttendancesController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/AttendancesResponse.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/model/AttendanceChange.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/repository/AttendanceChangesRepository.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/AttendanceIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/repository/AttendanceChangesRepsotioryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceServiceTest.kt

- Add date range filtering to the endpoint
- Use JPA relationship mapping 
- Add more unit tests

NN-2569 record attendance changes part2

---

helm_deploy/whereabouts-api/templates/deployment.yaml
helm_deploy/whereabouts-api/templates/ingress.yaml

Reverts ministryofjustice/whereabouts-api#180

Revert "DT-917: Switch out deprecated APIs"

---

helm_deploy/whereabouts-api/templates/deployment.yaml
helm_deploy/whereabouts-api/templates/ingress.yaml

Reverts ministryofjustice/whereabouts-api#181

Revert "Revert "DT-917: Switch out deprecated APIs""

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/LocationController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/LocationPrefixDto.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/LocationGroupServiceSelector.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/LocationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/LocationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/LocationServiceTest.kt
src/test/resources/uk/gov/justice/digital/hmpps/whereabouts/integration/MDI_location-prefix.json

- Returns the location prefix, translated from a group name. Eg MDI Houseblock 1 = MDI-1-

 NN-2925 return location prefix from group name

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/CourtController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/VideoLinkAppointmentLinker.kt
src/main/resources/db/migration/V16__video_link_bookint_contraints.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/AppointmentLinkerIntegrationTest.kt

* Chunking 
* Fix FK constraints

DCS-698 make video link bookings from appointments. 

---

build.gradle.kts

Reverts ministryofjustice/whereabouts-api#228

Revert "NN-3087 revert postgres update"

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/config/ResourceServerConfiguration.java
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/CourtController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/VideoLinkBookingResponse.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/attendance/AbsentReasonsDto.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/DocumentationIntegrationTest.kt

Also enabling OpenAPI and fixing required fields

DCS-748 Fixing broken swagger docs

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/CourtController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/CourtService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/controllers/CourtControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/CourtServiceTest.kt

The existing endpoint only returns bookings for Wandsworth

DCS-761 Adding endpoint to allow retrieving bookings for a prison. 

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/AppointmentLocationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/AppointmentLocationsServiceTest.kt

Description is all uppercase, general pattern is to prefer user description if available of fall back to description

DCS-794 Fix location description in new endpoint

---

src/main/resources/whereabouts/enabled.properties

Enabling HMP Featherstone for Wherabouts

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/VideoLinkBookingUpdateSpecification.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/CourtService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/controllers/CourtControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/CourtServiceTest.kt

The madeInCourt field shouldn't be changed after creation

DCS-811 removed madeInCourt flag when updating booking

---

src/main/resources/whereabouts/patterns/MDI.properties
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/AgencyIntegrationTest.kt

Adding the new HB8 for HMP Moorland

Update to HMP Moorland to add Houseblock 8 in Whereabouts

---

src/main/resources/whereabouts/enabled.properties

Enable HMP Highpoint (HPI) for Whereabouts

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/AppointmentLocationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/AppointmentLocationsServiceTest.kt

Stopped filtering appointments by appointmentTypeCode == 'VLB'.

DCS-899 :bug: Availability check not taking other appointments into account. 

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/CourtService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/repository/VideoLinkBookingRepositoryTest.kt

Make new ids appear in Application Insights VideoLinkBookingUpdated event.

DCS-888 Book a Video Link - Analytics. 

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

DCS-923: whereabouts-api. Dependencies version bump

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/PrisonController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/LocationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/controllers/PrisonControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/LocationServiceTest.kt

The rooms must have an eventType of 'APP' and a locationType of 'VIDE'

DCS-1042 new endpoint for getting rooms in prison

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/LocationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/VideoLinkBookingRoomsIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/LocationServiceTest.kt

The endpoint will return a user-friendly description of the video link booking room, is the description is available. Otherwise it will return the alternative, hyphenated description.

DCS-1056 /video-link-rooms/{agencyId} returns user-friendly description

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/VideoLinkBookingOptionsService.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/VideoLinkBookingOptionsFinder.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/CourtIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/wiremock/PrisonApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/VideoLinkBookingOptionsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/VideoLinkBookingOptionsFinderTest.kt

Improved prison-api query: Fetch appointments for specified locationIds only.

DCS-1042 Video link booking availability and alternatives

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceService.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/IEPWarningService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/AttendanceIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/IEPWarningServiceTest.kt

- SDI-129: ✨ Write sub reason to comment field when writing back to nomis
- SDI-129: ✨ Write sub reason to case note field too when writing case notes

pgp SDI 129 absent sub reason 4

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/AgencyController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/AppointmentController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/AppointmentsController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/AttendanceController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/AttendanceStatisticsController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/AttendancesController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/EventsController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/LocationController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/VideoLinkBookingController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/VideoLinkBookingEventController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/VideoLinkBookingRoomsController.kt

API parameters were incorrect, which is annoying when trying to call endpoints using postman

SDI-213: 📝 Fix swagger docs

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/AttendancesController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceService.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/PrisonApi.java
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/AttendancesIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceServiceTest.kt

- SDI-213: ⚰ Remove unused endpoint

SDI-213: ⚰ Remove unused endpoint

---

helm_deploy/README.md
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/whereabouts-api/Chart.yaml
helm_deploy/whereabouts-api/templates/NOTES.txt
helm_deploy/whereabouts-api/templates/_envs.tpl
helm_deploy/whereabouts-api/templates/_helpers.tpl
helm_deploy/whereabouts-api/templates/deployment.yaml
helm_deploy/whereabouts-api/templates/ingress.yaml
helm_deploy/whereabouts-api/templates/service.yaml
helm_deploy/whereabouts-api/values.yaml

Reverts ministryofjustice/whereabouts-api#468

Revert "NN-4278 generic service upgrade"

---

helm_deploy/whereabouts-api/Chart.yaml

Reverts ministryofjustice/whereabouts-api#473

Revert "NN-4278 use earlier chart version"

---

helm_deploy/README.md
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/whereabouts-api/Chart.yaml
helm_deploy/whereabouts-api/templates/NOTES.txt
helm_deploy/whereabouts-api/templates/_envs.tpl
helm_deploy/whereabouts-api/templates/_helpers.tpl
helm_deploy/whereabouts-api/templates/deployment.yaml
helm_deploy/whereabouts-api/templates/ingress.yaml
helm_deploy/whereabouts-api/templates/service.yaml
helm_deploy/whereabouts-api/values.yaml

Reverts ministryofjustice/whereabouts-api#472

Revert "NN-4278 generic service upgrade "

---

helm_deploy/README.md
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/whereabouts-api/Chart.yaml
helm_deploy/whereabouts-api/templates/NOTES.txt
helm_deploy/whereabouts-api/templates/_envs.tpl
helm_deploy/whereabouts-api/templates/_helpers.tpl
helm_deploy/whereabouts-api/templates/deployment.yaml
helm_deploy/whereabouts-api/templates/ingress_v1_2.yaml
helm_deploy/whereabouts-api/templates/service.yaml
helm_deploy/whereabouts-api/values.yaml

Reverts ministryofjustice/whereabouts-api#478

Revert "NN-4278"

---

helm_deploy/README.md
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/whereabouts-api/Chart.yaml
helm_deploy/whereabouts-api/templates/NOTES.txt
helm_deploy/whereabouts-api/templates/_envs.tpl
helm_deploy/whereabouts-api/templates/deployment.yaml
helm_deploy/whereabouts-api/templates/ingress_v1_2.yaml
helm_deploy/whereabouts-api/templates/service.yaml
helm_deploy/whereabouts-api/values.yaml

Reverts ministryofjustice/whereabouts-api#480

Revert "NN-4278 test"

---

helm_deploy/whereabouts-api/templates/ingress.yaml
helm_deploy/whereabouts-api/values.yaml

Reverts ministryofjustice/whereabouts-api#477

Revert "NN-4278 remove old ingress"

---

helm_deploy/values-dev.yaml

I will revert this change when kit arrives - but that may be up to a week away.

SAA-79: Temporary DEV access for developer with no VPN (delayed MOJ laptop)

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/config/VideoLinkBookingServiceForAppScope.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/SqsEventListener.kt

and no user token available
This matches the pattern used by the attendance service

DCS-1819 Fixing issue when deleting appointments

---

.circleci/config.yml
.trivyignore
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
helm_deploy/whereabouts-api/Chart.yaml

https://dsdmoj.atlassian.net/browse/NN-4627

NN-4627: bump dependencies and versions

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/VideoLinkBookingController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/PrisonApi.java
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/VideoLinkBookingMigrationService.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/controllers/VideoLinkBookingControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/PrisonApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingServiceTest.kt

This reverts commit 2a85d21d58d2e94fc56adb380b8d09fbc74570c6.

Revert "DCS-1913 removing unused endpoint (#519)"

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/VideoLinkBookingController.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/PrisonApi.java
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/VideoLinkBookingMigrationService.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/controllers/VideoLinkBookingControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/PrisonApiServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingServiceTest.kt

This reverts commit c8afb0374f76283376a7051da594d19c40a02713.

DCS-1913 removing unused endpoint

---

.trivyignore
build.gradle.kts
helm_deploy/whereabouts-api/Chart.yaml
helm_deploy/whereabouts-api/values.yaml

https://dsdmoj.atlassian.net/browse/NN-4730

NN-4730: bump helm charts and deps

---

helm_deploy/whereabouts-api/values.yaml

https://dsdmoj.atlassian.net/browse/NN-4731

NN-4731: revert Helm change from https://github.com/ministryofjustice/whereabouts-api/pull/528

---

helm_deploy/whereabouts-api/templates/dlq-cronjob.yaml
helm_deploy/whereabouts-api/values.yaml
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/config/ResourceServerConfiguration.java

https://dsdmoj.atlassian.net/browse/NN-4731

NN-4731: add DLQ CronJob

---

helm_deploy/whereabouts-api/templates/dlq-cronjob.yaml

https://dsdmoj.atlassian.net/browse/NN-4731

NN-4731: fix DLQ CronJob

---

database_refresh/02-cronjob.yaml
database_refresh/adhoc-db-refresh-job.yaml

https://dsdmoj.atlassian.net/browse/NN-4705

NN-4705: update database refresh CronJob docker image

---

build.gradle.kts
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/CourtHearingTypeController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/CourtHearingTypeIntegrationTest.kt
src/test/resources/uk/gov/justice/digital/hmpps/whereabouts/integration/court-hearing-types.json

DCS-2097 adding new endpoint to show court hearing types and library update

---

helm_deploy/values-preprod.yaml

https://dsdmoj.atlassian.net/browse/NN-5134

NN-5134: scale PreProd services from 4 to 2

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/whereabouts-api/values.yaml

https://dsdmoj.atlassian.net/browse/NN-5154
Same as https://github.com/ministryofjustice/keyworker-api/pull/456/files

NN-5154: use IRSA to connect to SQS and SNS - dev

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/whereabouts-api/values.yaml

https://dsdmoj.atlassian.net/browse/NN-5154

NN-5154: use IRSA to connect to SQS and SNS - PreProd and Prod

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/whereabouts-api/values.yaml

https://dsdmoj.atlassian.net/browse/HEAT-74

HEAT-74: update to use new service account from latest irsa terraform module

---

src/main/resources/db/migration/V59__add_and_update_courts_for_hmp_exeter.sql

Add some PPOC courts and update some others.
I have tried to make the codes similar to the ones for the existing magistrate courts with those names, except with PP instead of MC. The existing PPOC courts start with PPOC and then have a two letter code based on the location, so we could do that instead, but I feel like that doesn't allow for many unique codes.
MAP-271

MAP-271: Add and update some PPOC courts

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/model/VideoLinkBookingEventWithRoomNames.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/LocationService.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/PrisonApi.java
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/EventToCsvConverter.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingEventService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/VideoLinkBookingEventIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/wiremock/PrisonApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/LocationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/EventToCsvConverterTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingEventServiceTest.kt

Add columns for video link room names for main, pre & post hearings to BVL CSV downloads.

BVL report enhancements

---

src/main/resources/whereabouts/patterns/groups.properties

Please see Eddie for reasons - new locations at Ranby.

SAA-1343: Adding Ranby House block 8 as a new location for unlock

---

src/main/resources/db/migration/V64__add_courts_for_north_west_probation_teams.sql

PR for adding new courts to whereabouts-api. Needed by BVL

MAP-548 add new courts for north west probation teams

---

src/main/resources/whereabouts/patterns/groups.properties

Adding K-Wing for HMP Wealstun in the config file

Update config file for Whereabouts to add K-Wing for HMP Wealstun

---

README.md
docker-compose-test.yml
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/CourtIntegrationTest.kt

Also  resolves local testing issue with localstack and updates README to reflect accurate test instructions.

SAA-1535: Alternative times suggested after 10am for courts.

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/listeners/SqsOffenderEventListener.kt
src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingService.kt

Emails not being sent to one particular court when BVL appointments are being cancelled in Nomis

MAP-1464 add logs to help diagnose email bug

---

src/main/resources/db/migration/V67__add_courts_in_england.sql

[MAP-1563](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?quickFilter=3684&selectedIssue=MAP-1563)
These are the ones in bold at the bottom of the table
[MAP-1563]: https://dsdmoj.atlassian.net/browse/MAP-1563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1563 enabled 5 new courts

---

src/main/resources/db/migration/V68__remove_central_lincolnshire-probation-court.sql

[MAP-1567](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1567)
[MAP-1567]: https://dsdmoj.atlassian.net/browse/MAP-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1567 remove unused Central Lancashire court

---

helm_deploy/whereabouts-api/values.yaml
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/config/FeatureSwitchesTest.kt

The format of the env var for the feature toggle wasn't quite right.  This change should fix it (🤞 )

BAVL-41 fixing migration feature toggle.

---

src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkMigrationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/VideoLinkMigrationServiceTest.kt

Checking the court name on the actual booking or event is not enough to identify potential probation bookings.
We also need to check the court id against those set up in the enabled courts if there is no court name on the booking itself.

BAVL-43 enabled courts can also contain probation teams, we also need to check here to identify potential probation bookings when migrating.

---

helm_deploy/values-prod.yaml

Reverts ministryofjustice/whereabouts-api#737

Revert "BAVL-376 feature toggle should be on."

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Prep for Littlehey A&A rollout on the 21st Oct.

Disable whereabouts for Littlehey (also match preprod config to prod)

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

and match config values through all environments

Disable for pentonville
