ministryofjustice/whereabouts-api

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/AttendanceController.java
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/AttendanceDto.java
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceLocked.java
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceService.java
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/AttendanceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceServiceTest.kt
Returns `true` if the attendance was paid a day or more ago OR if the attendance was unpaid and happened 7 or more days ago. Else returns `false`. An update request to a locked attendance returns 400.
> Nn 1997 locked attendance api attribute

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceService.java
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/EventOutcome.java
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/NomisEventOutcomeMapper.java
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/AttendanceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/NomisEventOutcomeMapperTest.kt
This does two things:
1. Pushes the attendance comment to NOMIS (current only stored in this API's database)
2. Prepends a case note with the absence reason to provide more context for the IEP warning.
> Nn 1976 push att comment and update case note text

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceStatistics.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceStatisticsTest.kt
Currently when users select 'AM + PM' from the dropdown on the whereabouts statistics page, we're only counting people who have been unaccounted for for both periods. Instead, this is supposed to be a cumulative list. This fixes this by comparing number of schedules to number of attendances per booking id.
> Nn 2410 fix unaccounted for am pm bug

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/LocationController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/LocationIntegrationTest.kt
- src/test/resources/uk/gov/justice/digital/hmpps/whereabouts/integration/LEI_location_groups_agency_locname.json
- src/test/resources/uk/gov/justice/digital/hmpps/whereabouts/integration/RNI_location_groups_agency_locname.json
This was previously removed from whereabouts as it wasn't needed - but it is required now to get a list of locations for a group name so that we can retrieve the schedules for those locations.
> DT-526 Endpoint to retrieve agency locations by group

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/model/VideoLinkAppointment.kt
- src/main/resources/db/migration/V15__video_link_appointment_hearing_type_migration.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/repository/VideoLinkBookingRepositoryTest.kt
Fix problems with HearingType enum mapping:
1. Change this mapping so that persisted values are the strings 'PRE', 'MAIN' and 'POST'. 
1. Migrate the values in the video_link_appointment.hearing_type column from '0', '1', '2' to 'PRE', 'MAIN' and 'POST'.
> DCS-698 make video link bookings from appointments. 

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/config/ResourceServerConfiguration.java
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/AppointmentLocationsService.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/model.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/controllers/CourtControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/AppointmentLocationsServiceTest.kt
* LocalDate, LocalTime, LocalDate etcTime and ZonedDateTime now mapped to String instead of java.util.Date
* Fixed swagger doc for Location  by re-naming to LocationIdAndDescription because SpringFox couldn't handle  two classes having the same name.
> DCS-778 Fix swagger documentation

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/AppointmentController.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/AppointmentDtos.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AppointmentService.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/PrisonApiService.java
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/controllers/AppointmentControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/AppointmentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AppointmentServiceTest.kt
Add a new endpoint for appointment creation. At the moment all it does is ask prison API to create it. In later PR's were going to be storing information around recurring appointments.
> NN-3375: WIP 

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/VideoLinkAppointmentsSpecification.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/VideoLinkBookingSpecification.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/VideoLinkBookingUpdateSpecification.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/model/VideoLinkAppointment.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/model/VideoLinkBooking.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/repository/VideoLinkBookingRepository.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AppointmentService.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/ApplicationInsightsEventListener.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/CourtService.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/EventStoreListener.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingService.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/AppointmentLocationsService.kt
- src/main/resources/db/migration/V24__normalise_video_link_booking.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/AppointmentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/CourtIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/model/VideoLinkAppointmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/model/VideoLinkBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/repository/VideoLinkAppointmentRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/repository/VideoLinkBookingRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AppointmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/ApplicationInsightsEventListenerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/CourtServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/EventListenerTestData.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/EventStoreListenerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/AppointmentLocationsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/utils/DataHelpers.kt
* Move `bookingId`, `court`, `courtId`, `madeByTheCourt` and `createdByUsername` from child table `video_link_appointment` to the parent table `video_link_booking`.
* `video_link_booking` columns renamed for clarity: `court` -> `courtName`, `booking_id` -> `offender_booking_id`.
* Move data from child to parent.
* Drop child columns.
* Invert the links between `video_link_booking` and `video_link_appointment`: 
* add `video_link_booking_id` to `video_link_appointment` table. (FK to `video_link_booking` `id` column). 
* Populate `video_link_booking_id` column using values in `video_link_booking` (`pre`, `main`, `post`)
* drop `main`, `pre` and `post` columns (and FK relationships to `video_link_appointment`)
* Add database constraints where appropriate
* Align `VideoLinkBooking` and …
> DCS-703 Refactor - remove redundancy from video_link_appointment, video_link_booking

- src/main/resources/db/migration/V24__normalise_video_link_booking.sql
Make sure that there are no null `made_by_the_court` values in `video_link_booking` before adding a not null constraint to that column.
Null values should only appear in the 'dev' database.  preprod (and therefore prod) seem fine.
> DCS-703 Bug fix. 

- build.gradle.kts
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/VideoLinkBookingController.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/AppointmentLocationsService.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/LocationAndInterval.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/VideoLinkBookingOptionsService.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/DescribedLocationAndInterval.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/OptionsGenerator.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/VideoLinkBookingOptions.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/VideoLinkBookingOptionsFinder.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/VideoLinkBookingSearchSpecification.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/controllers/VideoLinkBookingControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/CourtIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/AppointmentLocationServiceTest2.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/AppointmentLocationsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/LocationAndIntervalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/locationfinder/VideoLinkBookingOptionsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/OptionsGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/TimelineTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/VideoLinkBookingOptionTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/VideoLinkBookingOptionsFinderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/VideoLinkBookingSearchSpecificationTest.kt
Have a look at story DCS-1042, then look at `VideoLinkBookingOptionsFinderTest`. That class tests the most of business logic for this story and is fairly easy to understand.  
The overall flow is: 
- `VideoLinkBookingController.findAvaliableVideoLinkBookingOptions` ->
- `AppointmentLocationsService.findVideoLinkBookingOptions()` ->
- `VideoLinkBookingOptionsService.findVideoLinkBookingOptions`
`VideoLinkBookingOptionsService.findVideoLinkBookingOptions()` does the interactions with prison-api and the database to retrieve and massage the data that `VideoLinkBookingOptionsFinder` uses to produce its result.
> DCS-1042 End point for finding Video Link Booking availability.

- src/main/resources/db/migration/V29__add_court_id_data_to_video_link_booking_event.sql
Assigning court_id will ensure CSV for reports and data studio will be more accurate.
There will be some anomalies where 'null' records will be in the outputs but that is because some records may have been created and then deleted.
> DCS-1057 db migration script to assign court_id to booking events

- src/main/resources/db/migration/V30__add_court_id_data_to_video_link_booking_event.sql
join on to enabled_courts by court name.  Matches a number of records where the original video_link_booking had been deleted,
> DCS-1057 Fix court_ids in video_link_booking_event data.

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/repository/VideoLinkBookingEventRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingEventServiceTest.kt
Add a sort to the VideoLinkBookingEvent query. Ensures that values always come back in the same order.
> DCS-976 Minor refinement to video link booking event reporting

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/VideoLinkBookingSpecification.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/VideoLinkBookingUpdateSpecification.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/dto/VideoLinkBookingSpecificationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/dto/VideoLinkBookingUpdateSpecificationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/CourtIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingServiceTest.kt
- Make `courtId` mandatory in `VideoLinkBookingUpdateSpecification`
- 2 line change to `VideoLinkBookingService` at line 90 to remove redundant null check.
- Add missing `@field:` prefix to `@Valid` annotations in `VideoLinkBookingSpecification` and `VideoLinkBookingUpdateSpecification` and add some tests to show that they work.
> DCS-1063 Change PUT /court/video-link-bookings/{videoBookingId} to make courtId mandatory

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/AttendancesController.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/dto/PrisonerScheduleDto.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceService.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/PrisonApi.java
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/AttendancesIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/wiremock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceServiceTest.kt
At present DPS fires off two calls - one to Prison API to get the scheduled activities and another to Whereabouts to get the attendances.  Whereabouts then calls Prison API to get the scheduled activities in order to return the offender details for the attendances.  This means that the same Prison API endpoint is called by both.  DPS then takes the difference between both lists to find out the prisoners that are unaccounted for - those that haven't attended.
This change then adds a new endpoint to return the list of prisoners that are unaccounted for, by doing the difference in Whereabouts instead.  It calls the same endpoint in Prison API.
> SDI-213: ✨ New endpoint for prisoners unaccounted for

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/AppointmentService.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/PrisonApi.java
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AppointmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/PrisonApiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingServiceTest.kt
BVL consumes events regarding appointments but is also sometimes the source of the event.
When BVL is the source of an event, there is a race conditions, where the event listener processes the event before BVL has committed its transaction which produced the event.
This is a bit of hack maybe, that will prevent raising events for appointments that BVL is modifying.
It has the knock on effect that other systems will not be notified of these
> DCS-1888 Prevent event generation when BVL makes requests

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/LocationService.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/VideoLinkBookingEventIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/LocationServiceTest.kt
- Don't use coroutines anymore, as they don't seem to work well with Spring MVC
- Only look up certain types of location (but don't filter for only VIDE)
> MAP-253: Improve BVL CSV download room name lookup performance

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkBookingEventService.kt
The eventId was not being copied over properly so it was missing from the CSV.
> MAP-253: Add eventId to BVL CSV

- helm_deploy/values-dev.yaml
- helm_deploy/whereabouts-api/Chart.yaml
- helm_deploy/whereabouts-api/values.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
2 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `9 => 0 (9 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist.
The following IPs have been …
> Migrating project to use groups in allowlist

- helm_deploy/whereabouts-api/values.yaml
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/listeners/SqsDomainEventListener.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/listeners/SqsOffenderEventListener.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/listeners/SqsDomainEventListenerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/listeners/SqsOffenderEventListenerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/model/VideoLinkBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/AttendanceServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/LocationGroupFromElite2ServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/LocationGroupFromPropertiesServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/CourtServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/VideoLinkBookingOptionsFinderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/vlboptionsfinder/VideoLinkBookingOptionsServiceTest.kt
- src/test/resources/application-test.yml
This change introduces a feature switch to turn off the listening to BVLS related events when the new replatformed BLVS service is made available in production.
When the new service is available it will be solely responsible for the processing of these events.
Note: this change also includes some unrelated linting fixes that showed up when compiling existing code (it was annoying me!)
> BAVL 251 adding feature switch to allow event subscription to be turned off for old BVLS when new BVLS service is available.

- helm_deploy/values-dev.yaml
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/listeners/SqsDomainEventListener.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/listeners/SqsOffenderEventListener.kt
This is trial run turning off of the BVLS feature flag which basically means ignoring certain events/messages for BVLS.
These events are to be processed by the re-platformed BLVS service when it goes live.
Events will not end up on the DLQ as they are still consumed but no processing is done on the back of receiving them.
Note this is in DEV only and will not impact preprod or prod, i.e it can be released to prod with this change if need be.
When confirmed as working a separate PR will be raised to turn it back on.
> BAVL-251 trial the turning off processing of events for BLVS in dev.

- helm_deploy/values-dev.yaml
This is reverting this (trial) feature flag change on a previous PR [here](https://github.com/ministryofjustice/whereabouts-api/pull/691).
> BAVL-251 turning flag back on for processing of events for BLVS in dev.

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/VideoLinkBookingRoomsController.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/PrisonApi.java
Calling /make-cell-move results in prisonApiService.putCellMove() call. 
Slow network could be the reason for the call to prison api returning 500 errors. 
Implemented shorter timeouts with greater retries.
> MAP-1557 change webclient options for a single endpoint

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/whereabouts-api/values.yaml
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/config/AsyncConfiguration.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/config/FeatureSwitches.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/controllers/VideoLinkMigrationController.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/repository/VideoLinkBookingEventRepository.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkMigrationService.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/events/OutboundEvents.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/events/OutboundEventsPublisher.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/events/OutboundEventsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/config/TestAsyncConfiguration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/VideoLinkMigrationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/court/OutboundEventsServiceTest.kt
* Adds an outbound events service/publisher and defines the migration event `whereabouts-api.videolink.migrate`
* Adds a feature switching service and switches outbound event ON in DEV only.
* Adds a paginated video link booking event selection repo method (mainStartTime > fromDate)
* Adds a new method to page through the CREATE events matching the criteria and emit an event for each booking.
* Tests
> BAVL-41: Migration trigger to select bookings and emit domain events

- helm_deploy/whereabouts-api/values.yaml
It looks like the config for publishing domain events for migration is not present in the helm config.  Added here.
Note this also requires a cloud platform change, linked [here](https://github.com/ministryofjustice/cloud-platform-environments/pull/26161).
> BAVL-41 missing domain events topic from config, needed so we can publish to it.

- helm_deploy/whereabouts-api/values.yaml
Reverts ministryofjustice/whereabouts-api#721
> Revert "BAVL-41 missing domain events topic from config, needed so we can publish to it."

- helm_deploy/values-dev.yaml
- helm_deploy/whereabouts-api/values.yaml
Having the SNS topic subscription in the overarching values.yaml file would potentially impact releasing to higher environments without the necessary cloud platform queue configuration in place.
> BAVL-41 move domain events topic subscription queue config to dev only, otherwise would impact release to higher environments.

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Should be merged as part of the A&A rollout process for IWI on Sep 20th (target date, may get put back). Now 27th
Also a minor change in here that will bring the preprod env up to date with the prod env for this rollout for IWI, and previously migrated Feltham FMI
> Disable IWI in whereabouts due to DPS A&A rollout

- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/listeners/SqsDomainEventListener.kt
- src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/court/VideoLinkMigrationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/integration/VideoLinkMigrateIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/whereabouts/services/VideoLinkMigrationServiceTest.kt
During migration testing a discrepancy occurred where we were unable to migrate 1830 old bookings
We have identified these bookings as deleted but don’t they have any corresponding delete event.
In order to migrate these we create a FAKE delete event for these bookings.
> BAVL-376 migration changes to cater for deleted bookings missing their corresponding delete event.
